### ISSUE TITLE
newest p3 commit (457e07c readme changes - DipLeChip 0ffacd6 Merge pull request #20 from DipLeChip/patch-6 - gcurtiss) will  flood the console with random bullshit

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#21]
[21:05:25 WARN]: [protocol3] Task #254 for protocol3 v1.0.0 generated an exception
java.lang.NumberFormatException: For input string: "false"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at protocol3.events.SpeedLimit.lambda$scheduleSlTask$2(SpeedLimit.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-528]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-528]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Paper-528]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-528]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-528]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-528]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-528]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by willcannotpaythebills** [comment]
^ will spam that every second. i can upload my log if u want.

**Comment by willcannotpaythebills** [comment]
[latest.log](https://github.com/gcurtiss/protocol3/files/6161276/latest.log)

**Comment by gcurtiss** [comment]
fixed in 0ffacd6

**Comment by gcurtiss** [comment]
i lied it's fixed in 86393d2
